import type { Metadata } from "next";
import { Bowlby_One, Architects_Daughter} from "next/font/google";
import "./globals.css";
import Navigation from "../../src/components/navbar";
import * as React from "react";
import InfoBar from "../components/InfoBar";
import Footer from "../components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const bowlbyOne = Bowlby_One({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bowlby'
})

const architectsDaughter = Architects_Daughter({
  weight: '400', 
  subsets: ['latin'],
  variable: '--font-architects'
})


export const metadata: Metadata = {
  title: "Rettungsanker-Freiburg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
      <body className={`${bowlbyOne.variable} ${architectsDaughter.variable} antialiased`}>
        <Navigation />
        <InfoBar />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>    
  );
}
