import type { Metadata } from "next";
import { Bowlby_One_SC, Architects_Daughter} from "next/font/google";
import "./globals.css";
import Navigation from "../../src/components/navbar";
import * as React from "react";

const bowlbyOne = Bowlby_One_SC({
  variable: "--font-bowlby-one",
  subsets: ["latin"],
  weight: "400"
});

const architectsDaughter = Architects_Daughter({
  variable: "--font-architects-daughter",
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Rettungsanker-Freiburg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlbyOne.variable} ${architectsDaughter.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
