import localFont from 'next/font/local';
import '../globals.css';
import Header from '@/components/Header';
import { ThemeProvider } from 'next-themes';
import ThemeCom from '@/components/ThemeCom';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeModeScript } from 'flowbite-react';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Rettungsanker Blog',
  description: 'Generated by create next app',
};

/**
 * Root layout for the blog section.
 *
 * Wraps page content with application-level providers and layout chrome:
 * - ClerkProvider for authentication context
 * - <html lang="en" suppressHydrationWarning> and a ThemeModeScript injected in <head>
 * - A body element that applies font and antialiasing classes
 * - ThemeProvider and ThemeCom wrappers that render the site Header, the page children, and Footer
 *
 * @param {Object} props - Component props.
 * @param {import('react').ReactNode} props.children - The nested page content to be rendered inside the layout.
 * @returns {JSX.Element} The composed root layout element for the blog route.
 */
export default function BlogLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en' >
        <head>
          <ThemeModeScript />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider>
            <ThemeCom>
              <Header />
              {children}
              <Footer />
            </ThemeCom>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
